/**
 * Swagger Easeat Auth API
 * This is a microservice for managing authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthApi from './api/AuthApi';
import PublicApi from './api/PublicApi';
import SponsoApi from './api/SponsoApi';
import MongoModelsOrder from "./model/MongoModelsOrder";
import MongoModelsOrderStatus from "./model/MongoModelsOrderStatus";
import OrderApi from "./api/OrderApi";
import MongoModelsOrderPositionHistory from "./model/MongoModelsOrderPositionHistory";
import OrderPositionApi from "./api/OrderPositionApi";
import ModelMenuitem from "./model/ModelMenuitem";
import ModelRestaurant from "./model/ModelRestaurant";
import RestaurantApi from "./api/RestaurantApi";

/**
* This is a microservice for managing authentication.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SwaggerEaseatAuthApi = require('index'); // See note below*.
* var xxxSvc = new SwaggerEaseatAuthApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SwaggerEaseatAuthApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SwaggerEaseatAuthApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SwaggerEaseatAuthApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
  /**
   * The ApiClient constructor.
   * @property {module:ApiClient}
   */
  ApiClient,

  /**
   * The AuthApi service constructor.
   * @property {module:api/AuthApi}
   */
  AuthApi,

  /**
   * The PublicApi service constructor.
   * @property {module:api/PublicApi}
   */
  PublicApi,

  /**
   * The SponsoApi service constructor.
   * @property {module:api/SponsoApi}
   */
  SponsoApi,

  /**
   * The MongoModelsOrder model constructor.
   * @property {module:model/MongoModelsOrder}
   */
  MongoModelsOrder,

  /**
   * The MongoModelsOrderStatus model constructor.
   * @property {module:model/MongoModelsOrderStatus}
   */
  MongoModelsOrderStatus,

  /**
   * The OrderApi service constructor.
   * @property {module:api/OrderApi}
   */
  OrderApi,

  /**
   * The MongoModelsOrderPositionHistory model constructor.
   * @property {module:model/MongoModelsOrderPositionHistory}
   */
  MongoModelsOrderPositionHistory,

  /**
   * The OrderPositionApi service constructor.
   * @property {module:api/OrderPositionApi}
   */
  OrderPositionApi,

  /**
   * The ModelMenuitem model constructor.
   * @property {module:model/ModelMenuitem}
   */
  ModelMenuitem,

  /**
   * The ModelRestaurant model constructor.
   * @property {module:model/ModelRestaurant}
   */
  ModelRestaurant,

  /**
   * The RestaurantApi service constructor.
   * @property {module:api/RestaurantApi}
   */
  RestaurantApi,
};
