/**
 * Swagger Easeat delivery persons microservice
 * This is a microservice for managing delivery persons
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomModelsDeliveryPersonStatus model module.
 * @module model/CustomModelsDeliveryPersonStatus
 * @version 2.0
 */
class CustomModelsDeliveryPersonStatus {
    /**
     * Constructs a new <code>CustomModelsDeliveryPersonStatus</code>.
     * @alias module:model/CustomModelsDeliveryPersonStatus
     */
    constructor() { 
        
        CustomModelsDeliveryPersonStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomModelsDeliveryPersonStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomModelsDeliveryPersonStatus} obj Optional instance to populate.
     * @return {module:model/CustomModelsDeliveryPersonStatus} The populated <code>CustomModelsDeliveryPersonStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomModelsDeliveryPersonStatus();

            if (data.hasOwnProperty('idUser')) {
                obj['idUser'] = ApiClient.convertToType(data['idUser'], 'Number');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomModelsDeliveryPersonStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomModelsDeliveryPersonStatus</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {Number} idUser
 */
CustomModelsDeliveryPersonStatus.prototype['idUser'] = undefined;

/**
 * @member {Number} latitude
 */
CustomModelsDeliveryPersonStatus.prototype['latitude'] = undefined;

/**
 * @member {Number} longitude
 */
CustomModelsDeliveryPersonStatus.prototype['longitude'] = undefined;

/**
 * @member {String} status
 */
CustomModelsDeliveryPersonStatus.prototype['status'] = undefined;






export default CustomModelsDeliveryPersonStatus;

