/**
 * Swagger Easeat delivery persons microservice
 * This is a microservice for managing delivery persons
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeliverypersonSetStatusStatusPostRequest model module.
 * @module model/DeliverypersonSetStatusStatusPostRequest
 * @version 2.0
 */
class DeliverypersonSetStatusStatusPostRequest {
    /**
     * Constructs a new <code>DeliverypersonSetStatusStatusPostRequest</code>.
     * @alias module:model/DeliverypersonSetStatusStatusPostRequest
     * @param longitude {String} Longitude of the delivery person
     * @param latitude {String} Latitude of the delivery person
     */
    constructor(longitude, latitude) { 
        
        DeliverypersonSetStatusStatusPostRequest.initialize(this, longitude, latitude);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, longitude, latitude) { 
        obj['longitude'] = longitude;
        obj['latitude'] = latitude;
    }

    /**
     * Constructs a <code>DeliverypersonSetStatusStatusPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeliverypersonSetStatusStatusPostRequest} obj Optional instance to populate.
     * @return {module:model/DeliverypersonSetStatusStatusPostRequest} The populated <code>DeliverypersonSetStatusStatusPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliverypersonSetStatusStatusPostRequest();

            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'String');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeliverypersonSetStatusStatusPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeliverypersonSetStatusStatusPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeliverypersonSetStatusStatusPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['longitude'] && !(typeof data['longitude'] === 'string' || data['longitude'] instanceof String)) {
            throw new Error("Expected the field `longitude` to be a primitive type in the JSON string but got " + data['longitude']);
        }
        // ensure the json data is a string
        if (data['latitude'] && !(typeof data['latitude'] === 'string' || data['latitude'] instanceof String)) {
            throw new Error("Expected the field `latitude` to be a primitive type in the JSON string but got " + data['latitude']);
        }

        return true;
    }


}

DeliverypersonSetStatusStatusPostRequest.RequiredProperties = ["longitude", "latitude"];

/**
 * Longitude of the delivery person
 * @member {String} longitude
 */
DeliverypersonSetStatusStatusPostRequest.prototype['longitude'] = undefined;

/**
 * Latitude of the delivery person
 * @member {String} latitude
 */
DeliverypersonSetStatusStatusPostRequest.prototype['latitude'] = undefined;






export default DeliverypersonSetStatusStatusPostRequest;

