/**
 * Swagger Easeat restaurant microservice
 * This is a microservice for managing restaurants
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelDayOpeningHours model module.
 * @module model/ModelDayOpeningHours
 * @version 2.0
 */
class ModelDayOpeningHours {
    /**
     * Constructs a new <code>ModelDayOpeningHours</code>.
     * @alias module:model/ModelDayOpeningHours
     */
    constructor() { 
        
        ModelDayOpeningHours.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelDayOpeningHours</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelDayOpeningHours} obj Optional instance to populate.
     * @return {module:model/ModelDayOpeningHours} The populated <code>ModelDayOpeningHours</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelDayOpeningHours();

            if (data.hasOwnProperty('close')) {
                obj['close'] = ApiClient.convertToType(data['close'], 'String');
            }
            if (data.hasOwnProperty('open')) {
                obj['open'] = ApiClient.convertToType(data['open'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModelDayOpeningHours</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModelDayOpeningHours</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['close'] && !(typeof data['close'] === 'string' || data['close'] instanceof String)) {
            throw new Error("Expected the field `close` to be a primitive type in the JSON string but got " + data['close']);
        }
        // ensure the json data is a string
        if (data['open'] && !(typeof data['open'] === 'string' || data['open'] instanceof String)) {
            throw new Error("Expected the field `open` to be a primitive type in the JSON string but got " + data['open']);
        }

        return true;
    }


}



/**
 * @member {String} close
 */
ModelDayOpeningHours.prototype['close'] = undefined;

/**
 * @member {String} open
 */
ModelDayOpeningHours.prototype['open'] = undefined;






export default ModelDayOpeningHours;

