/**
 * Swagger Easeat restaurant microservice
 * This is a microservice for managing restaurants
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelRestaurant model module.
 * @module model/ModelRestaurant
 * @version 2.0
 */
class ModelRestaurant {
    /**
     * Constructs a new <code>ModelRestaurant</code>.
     * @alias module:model/ModelRestaurant
     */
    constructor() { 
        
        ModelRestaurant.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelRestaurant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelRestaurant} obj Optional instance to populate.
     * @return {module:model/ModelRestaurant} The populated <code>ModelRestaurant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelRestaurant();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('id_restaurant')) {
                obj['id_restaurant'] = ApiClient.convertToType(data['id_restaurant'], 'Number');
            }
            if (data.hasOwnProperty('localisation_latitude')) {
                obj['localisation_latitude'] = ApiClient.convertToType(data['localisation_latitude'], 'Number');
            }
            if (data.hasOwnProperty('localisation_longitude')) {
                obj['localisation_longitude'] = ApiClient.convertToType(data['localisation_longitude'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('opening_hours')) {
                obj['opening_hours'] = ApiClient.convertToType(data['opening_hours'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('picture')) {
                obj['picture'] = ApiClient.convertToType(data['picture'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModelRestaurant</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModelRestaurant</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['opening_hours'] && !(typeof data['opening_hours'] === 'string' || data['opening_hours'] instanceof String)) {
            throw new Error("Expected the field `opening_hours` to be a primitive type in the JSON string but got " + data['opening_hours']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['picture'] && !(typeof data['picture'] === 'string' || data['picture'] instanceof String)) {
            throw new Error("Expected the field `picture` to be a primitive type in the JSON string but got " + data['picture']);
        }

        return true;
    }


}



/**
 * @member {String} address
 */
ModelRestaurant.prototype['address'] = undefined;

/**
 * @member {Number} id_restaurant
 */
ModelRestaurant.prototype['id_restaurant'] = undefined;

/**
 * @member {Number} localisation_latitude
 */
ModelRestaurant.prototype['localisation_latitude'] = undefined;

/**
 * @member {Number} localisation_longitude
 */
ModelRestaurant.prototype['localisation_longitude'] = undefined;

/**
 * @member {String} name
 */
ModelRestaurant.prototype['name'] = undefined;

/**
 * @member {String} opening_hours
 */
ModelRestaurant.prototype['opening_hours'] = undefined;

/**
 * @member {String} phone
 */
ModelRestaurant.prototype['phone'] = undefined;

/**
 * @member {String} picture
 */
ModelRestaurant.prototype['picture'] = undefined;






export default ModelRestaurant;

