/**
 * Swagger Easeat restaurant microservice
 * This is a microservice for managing restaurants
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelMenuitem model module.
 * @module model/ModelMenuitem
 * @version 2.0
 */
class ModelMenuitem {
    /**
     * Constructs a new <code>ModelMenuitem</code>.
     * @alias module:model/ModelMenuitem
     */
    constructor() { 
        
        ModelMenuitem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelMenuitem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelMenuitem} obj Optional instance to populate.
     * @return {module:model/ModelMenuitem} The populated <code>ModelMenuitem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelMenuitem();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id_menu_item')) {
                obj['id_menu_item'] = ApiClient.convertToType(data['id_menu_item'], 'Number');
            }
            if (data.hasOwnProperty('id_restaurant')) {
                obj['id_restaurant'] = ApiClient.convertToType(data['id_restaurant'], 'Number');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModelMenuitem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModelMenuitem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {String} created_at
 */
ModelMenuitem.prototype['created_at'] = undefined;

/**
 * @member {String} description
 */
ModelMenuitem.prototype['description'] = undefined;

/**
 * @member {Number} id_menu_item
 */
ModelMenuitem.prototype['id_menu_item'] = undefined;

/**
 * @member {Number} id_restaurant
 */
ModelMenuitem.prototype['id_restaurant'] = undefined;

/**
 * @member {String} image
 */
ModelMenuitem.prototype['image'] = undefined;

/**
 * @member {String} name
 */
ModelMenuitem.prototype['name'] = undefined;

/**
 * @member {Number} price
 */
ModelMenuitem.prototype['price'] = undefined;






export default ModelMenuitem;

