/**
 * Swagger Easeat restaurant microservice
 * This is a microservice for managing restaurant opening hours
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelOpeningHours model module.
 * @module model/ModelOpeningHours
 * @version 2.0
 */
class ModelOpeningHours {
    /**
     * Constructs a new <code>ModelOpeningHours</code>.
     * @alias module:model/ModelOpeningHours
     */
    constructor() { 
        
        ModelOpeningHours.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelOpeningHours</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelOpeningHours} obj Optional instance to populate.
     * @return {module:model/ModelOpeningHours} The populated <code>ModelOpeningHours</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelOpeningHours();

            if (data.hasOwnProperty('id_restaurant')) {
                obj['id_restaurant'] = ApiClient.convertToType(data['id_restaurant'], 'Number');
            }
            if (data.hasOwnProperty('day_of_week')) {
                obj['day_of_week'] = ApiClient.convertToType(data['day_of_week'], 'Number');
            }
            if (data.hasOwnProperty('opening_time')) {
                obj['opening_time'] = ApiClient.convertToType(data['opening_time'], 'String');
            }
            if (data.hasOwnProperty('closing_time')) {
                obj['closing_time'] = ApiClient.convertToType(data['closing_time'], 'String');
            }
            if (data.hasOwnProperty('is_closed')) {
                obj['is_closed'] = ApiClient.convertToType(data['is_closed'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModelOpeningHours</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModelOpeningHours</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['opening_time'] && !(typeof data['opening_time'] === 'string' || data['opening_time'] instanceof String)) {
            throw new Error("Expected the field `opening_time` to be a primitive type in the JSON string but got " + data['opening_time']);
        }
        // ensure the json data is a string
        if (data['closing_time'] && !(typeof data['closing_time'] === 'string' || data['closing_time'] instanceof String)) {
            throw new Error("Expected the field `closing_time` to be a primitive type in the JSON string but got " + data['closing_time']);
        }

        return true;
    }
}

/**
 * @member {Number} id_restaurant
 */
ModelOpeningHours.prototype['id_restaurant'] = undefined;

/**
 * @member {Number} day_of_week
 */
ModelOpeningHours.prototype['day_of_week'] = undefined;

/**
 * @member {String} opening_time
 */
ModelOpeningHours.prototype['opening_time'] = undefined;

/**
 * @member {String} closing_time
 */
ModelOpeningHours.prototype['closing_time'] = undefined;

/**
 * @member {Boolean} is_closed
 */
ModelOpeningHours.prototype['is_closed'] = undefined;

export default ModelOpeningHours; 