/**
 * Swagger Easeat Order position API
 * This is a microservice for managing orders positions
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MongoModelsOrderPositionHistory model module.
 * @module model/MongoModelsOrderPositionHistory
 * @version 2.0
 */
class MongoModelsOrderPositionHistory {
    /**
     * Constructs a new <code>MongoModelsOrderPositionHistory</code>.
     * @alias module:model/MongoModelsOrderPositionHistory
     */
    constructor() { 
        
        MongoModelsOrderPositionHistory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MongoModelsOrderPositionHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MongoModelsOrderPositionHistory} obj Optional instance to populate.
     * @return {module:model/MongoModelsOrderPositionHistory} The populated <code>MongoModelsOrderPositionHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MongoModelsOrderPositionHistory();

            if (data.hasOwnProperty('datetime')) {
                obj['datetime'] = ApiClient.convertToType(data['datetime'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'Number');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MongoModelsOrderPositionHistory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MongoModelsOrderPositionHistory</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['datetime'] && !(typeof data['datetime'] === 'string' || data['datetime'] instanceof String)) {
            throw new Error("Expected the field `datetime` to be a primitive type in the JSON string but got " + data['datetime']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['position'] && !(typeof data['position'] === 'string' || data['position'] instanceof String)) {
            throw new Error("Expected the field `position` to be a primitive type in the JSON string but got " + data['position']);
        }

        return true;
    }


}



/**
 * @member {String} datetime
 */
MongoModelsOrderPositionHistory.prototype['datetime'] = undefined;

/**
 * @member {String} id
 */
MongoModelsOrderPositionHistory.prototype['id'] = undefined;

/**
 * @member {Number} order_id
 */
MongoModelsOrderPositionHistory.prototype['order_id'] = undefined;

/**
 * @member {String} position
 */
MongoModelsOrderPositionHistory.prototype['position'] = undefined;






export default MongoModelsOrderPositionHistory;

