/**
 * Swagger Easeat Order microservice API
 * This is a microservice for managing orders in the Easeat application.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MongoModelsOrderStatus from './MongoModelsOrderStatus';

/**
 * The MongoModelsOrder model module.
 * @module model/MongoModelsOrder
 * @version 2.0
 */
class MongoModelsOrder {
    /**
     * Constructs a new <code>MongoModelsOrder</code>.
     * @alias module:model/MongoModelsOrder
     */
    constructor() { 
        
        MongoModelsOrder.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MongoModelsOrder</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MongoModelsOrder} obj Optional instance to populate.
     * @return {module:model/MongoModelsOrder} The populated <code>MongoModelsOrder</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MongoModelsOrder();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'Number');
            }
            if (data.hasOwnProperty('delivery_at')) {
                obj['delivery_at'] = ApiClient.convertToType(data['delivery_at'], 'String');
            }
            if (data.hasOwnProperty('delivery_person_id')) {
                obj['delivery_person_id'] = ApiClient.convertToType(data['delivery_person_id'], 'Number');
            }
            if (data.hasOwnProperty('restaurant_id')) {
                obj['restaurant_id'] = ApiClient.convertToType(data['restaurant_id'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = MongoModelsOrderStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MongoModelsOrder</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MongoModelsOrder</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['_id'] && !(typeof data['_id'] === 'string' || data['_id'] instanceof String)) {
            throw new Error("Expected the field `_id` to be a primitive type in the JSON string but got " + data['_id']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['delivery_at'] && !(typeof data['delivery_at'] === 'string' || data['delivery_at'] instanceof String)) {
            throw new Error("Expected the field `delivery_at` to be a primitive type in the JSON string but got " + data['delivery_at']);
        }

        return true;
    }


}



/**
 * @member {String} _id
 */
MongoModelsOrder.prototype['_id'] = undefined;

/**
 * @member {String} created_at
 */
MongoModelsOrder.prototype['created_at'] = undefined;

/**
 * @member {Number} customer_id
 */
MongoModelsOrder.prototype['customer_id'] = undefined;

/**
 * @member {String} delivery_at
 */
MongoModelsOrder.prototype['delivery_at'] = undefined;

/**
 * @member {Number} delivery_person_id
 */
MongoModelsOrder.prototype['delivery_person_id'] = undefined;

/**
 * @member {Number} restaurant_id
 */
MongoModelsOrder.prototype['restaurant_id'] = undefined;

/**
 * @member {module:model/MongoModelsOrderStatus} status
 */
MongoModelsOrder.prototype['status'] = undefined;






export default MongoModelsOrder;

