/**
 * Swagger Easeat Order microservice API
 * This is a microservice for managing orders in the Easeat application.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: benjamin.guerre@viacesi.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MongoModelsOrderStatus.
* @enum {}
* @readonly
*/
export default class MongoModelsOrderStatus {
    
        /**
         * value: "AwaitingValidation"
         * @const
         */
        "OrderStatusAwaitingValidation" = "AwaitingValidation";

    
        /**
         * value: "InPreparation"
         * @const
         */
        "OrderStatusInPreparation" = "InPreparation";

    
        /**
         * value: "AwaitingCourier"
         * @const
         */
        "OrderStatusAwaitingCourier" = "AwaitingCourier";

    
        /**
         * value: "InDelivery"
         * @const
         */
        "OrderStatusInDelivery" = "InDelivery";

    
        /**
         * value: "Delivered"
         * @const
         */
        "OrderStatusDelivered" = "Delivered";

    
        /**
         * value: "Closed"
         * @const
         */
        "OrderStatusClosed" = "Closed";

    

    /**
    * Returns a <code>MongoModelsOrderStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MongoModelsOrderStatus} The enum <code>MongoModelsOrderStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

