package constants

const (
	API_GATEWAY_PORT_ENV       = "API_GATEWAY_PORT"
	API_GATEWAY_ADDR_ENV       = "API_GATEWAY_ADDR"
	MICRO_SERV_USERS_PORT_ENV  = "MICRO_SERV_USERS_PORT"
	MICRO_SERV_USERS_ADDR_ENV  = "MICRO_SERV_USERS_ADDR"
	MONGO_HOST_ENV             = "MONGO_HOST"
	MONGO_PORT_ENV             = "MONGO_PORT"
	MONGO_INITDB_ROOT_USERNAME = "MONGO_INITDB_ROOT_USERNAME"
	MONGO_INITDB_ROOT_PASSWORD = "MONGO_INITDB_ROOT_PASSWORD"
)
