// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePosseder = "posseder"

// Posseder mapped from table <posseder>
type Posseder struct {
	IDUser       int32 `gorm:"column:id_user;primaryKey" json:"id_user"`
	IDRestaurant int32 `gorm:"column:id_restaurant;primaryKey" json:"id_restaurant"`
}

// TableName Posseder's table name
func (*Posseder) TableName() string {
	return TableNamePosseder
}
