// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRestaurant = "restaurants"

// Restaurant mapped from table <restaurants>
type Restaurant struct {
	IDRestaurant          int32   `gorm:"column:id_restaurant;primaryKey;autoIncrement:true" json:"id_restaurant"`
	Name                  string  `gorm:"column:name;not null" json:"name"`
	Address               string  `gorm:"column:address;not null" json:"address"`
	Picture               string  `gorm:"column:picture" json:"picture"`
	LocalisationLatitude  float64 `gorm:"column:localisation_latitude" json:"localisation_latitude"`
	LocalisationLongitude float64 `gorm:"column:localisation_longitude" json:"localisation_longitude"`
	Phone                 string  `gorm:"column:phone" json:"phone"`
	OpeningHours          string  `gorm:"column:opening_hours" json:"opening_hours"`
}

// Column names for Restaurant defined as constants for consistency and immutability.
const (
	RestaurantColumnIDRestaurant          = "id_restaurant"
	RestaurantColumnName                  = "name"
	RestaurantColumnAddress               = "address"
	RestaurantColumnPicture               = "picture"
	RestaurantColumnLocalisationLatitude  = "localisation_latitude"
	RestaurantColumnLocalisationLongitude = "localisation_longitude"
	RestaurantColumnPhone                 = "phone"
	RestaurantColumnOpeningHours          = "opening_hours"
)

// TableName Restaurant's table name
func (*Restaurant) TableName() string {
	return TableNameRestaurant
}
