// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"sqlDB/dao/model"
)

func newPosseder(db *gorm.DB, opts ...gen.DOOption) posseder {
	_posseder := posseder{}

	_posseder.possederDo.UseDB(db, opts...)
	_posseder.possederDo.UseModel(&model.Posseder{})

	tableName := _posseder.possederDo.TableName()
	_posseder.ALL = field.NewAsterisk(tableName)
	_posseder.IDUser = field.NewInt32(tableName, "id_user")
	_posseder.IDRestaurant = field.NewInt32(tableName, "id_restaurant")

	_posseder.fillFieldMap()

	return _posseder
}

type posseder struct {
	possederDo possederDo

	ALL          field.Asterisk
	IDUser       field.Int32
	IDRestaurant field.Int32

	fieldMap map[string]field.Expr
}

func (p posseder) Table(newTableName string) *posseder {
	p.possederDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p posseder) As(alias string) *posseder {
	p.possederDo.DO = *(p.possederDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *posseder) updateTableName(table string) *posseder {
	p.ALL = field.NewAsterisk(table)
	p.IDUser = field.NewInt32(table, "id_user")
	p.IDRestaurant = field.NewInt32(table, "id_restaurant")

	p.fillFieldMap()

	return p
}

func (p *posseder) WithContext(ctx context.Context) *possederDo { return p.possederDo.WithContext(ctx) }

func (p posseder) TableName() string { return p.possederDo.TableName() }

func (p posseder) Alias() string { return p.possederDo.Alias() }

func (p posseder) Columns(cols ...field.Expr) gen.Columns { return p.possederDo.Columns(cols...) }

func (p *posseder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *posseder) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["id_user"] = p.IDUser
	p.fieldMap["id_restaurant"] = p.IDRestaurant
}

func (p posseder) clone(db *gorm.DB) posseder {
	p.possederDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p posseder) replaceDB(db *gorm.DB) posseder {
	p.possederDo.ReplaceDB(db)
	return p
}

type possederDo struct{ gen.DO }

func (p possederDo) Debug() *possederDo {
	return p.withDO(p.DO.Debug())
}

func (p possederDo) WithContext(ctx context.Context) *possederDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p possederDo) ReadDB() *possederDo {
	return p.Clauses(dbresolver.Read)
}

func (p possederDo) WriteDB() *possederDo {
	return p.Clauses(dbresolver.Write)
}

func (p possederDo) Session(config *gorm.Session) *possederDo {
	return p.withDO(p.DO.Session(config))
}

func (p possederDo) Clauses(conds ...clause.Expression) *possederDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p possederDo) Returning(value interface{}, columns ...string) *possederDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p possederDo) Not(conds ...gen.Condition) *possederDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p possederDo) Or(conds ...gen.Condition) *possederDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p possederDo) Select(conds ...field.Expr) *possederDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p possederDo) Where(conds ...gen.Condition) *possederDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p possederDo) Order(conds ...field.Expr) *possederDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p possederDo) Distinct(cols ...field.Expr) *possederDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p possederDo) Omit(cols ...field.Expr) *possederDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p possederDo) Join(table schema.Tabler, on ...field.Expr) *possederDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p possederDo) LeftJoin(table schema.Tabler, on ...field.Expr) *possederDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p possederDo) RightJoin(table schema.Tabler, on ...field.Expr) *possederDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p possederDo) Group(cols ...field.Expr) *possederDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p possederDo) Having(conds ...gen.Condition) *possederDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p possederDo) Limit(limit int) *possederDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p possederDo) Offset(offset int) *possederDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p possederDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *possederDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p possederDo) Unscoped() *possederDo {
	return p.withDO(p.DO.Unscoped())
}

func (p possederDo) Create(values ...*model.Posseder) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p possederDo) CreateInBatches(values []*model.Posseder, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p possederDo) Save(values ...*model.Posseder) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p possederDo) First() (*model.Posseder, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Posseder), nil
	}
}

func (p possederDo) Take() (*model.Posseder, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Posseder), nil
	}
}

func (p possederDo) Last() (*model.Posseder, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Posseder), nil
	}
}

func (p possederDo) Find() ([]*model.Posseder, error) {
	result, err := p.DO.Find()
	return result.([]*model.Posseder), err
}

func (p possederDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Posseder, err error) {
	buf := make([]*model.Posseder, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p possederDo) FindInBatches(result *[]*model.Posseder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p possederDo) Attrs(attrs ...field.AssignExpr) *possederDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p possederDo) Assign(attrs ...field.AssignExpr) *possederDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p possederDo) Joins(fields ...field.RelationField) *possederDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p possederDo) Preload(fields ...field.RelationField) *possederDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p possederDo) FirstOrInit() (*model.Posseder, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Posseder), nil
	}
}

func (p possederDo) FirstOrCreate() (*model.Posseder, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Posseder), nil
	}
}

func (p possederDo) FindByPage(offset int, limit int) (result []*model.Posseder, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p possederDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p possederDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p possederDo) Delete(models ...*model.Posseder) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *possederDo) withDO(do gen.Dao) *possederDo {
	p.DO = *do.(*gen.DO)
	return p
}
