basePath: /order
definitions:
  mongoModels.Order:
    properties:
      _id:
        type: string
      created_at:
        type: string
      customer_id:
        type: integer
      delivery_at:
        type: string
      delivery_person_id:
        type: integer
      restaurant_id:
        type: integer
      status:
        $ref: '#/definitions/mongoModels.OrderStatus'
    type: object
  mongoModels.OrderStatus:
    enum:
    - AwaitingValidation
    - InPreparation
    - AwaitingCourier
    - InDelivery
    - Delivered
    - Closed
    type: string
    x-enum-varnames:
    - OrderStatusAwaitingValidation
    - OrderStatusInPreparation
    - OrderStatusAwaitingCourier
    - OrderStatusInDelivery
    - OrderStatusDelivered
    - OrderStatusClosed
host: localhost:8093
info:
  contact:
    email: benjamin.guerre@viacesi.fr
    name: Groupe 2 FISA INFO A4 CESI (2025)
    url: https://contact.easeat.fr
  description: This is a microservice for managing orders in the Easeat application.
  title: Swagger Easeat Order microservice API
  version: "2.0"
paths:
  /:
    patch:
      consumes:
      - application/json
      description: Update an order
      parameters:
      - description: Order object
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/mongoModels.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mongoModels.Order'
      security:
      - BearerAuth: []
      summary: Update an order
      tags:
      - order
    post:
      consumes:
      - application/json
      description: Create an order
      parameters:
      - description: Order object
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/mongoModels.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mongoModels.Order'
      security:
      - BearerAuth: []
      summary: Create an order
      tags:
      - order
  /{orderId}:
    delete:
      consumes:
      - application/json
      description: Delete an order
      parameters:
      - description: Order ID
        in: path
        name: orderId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Delete an order
      tags:
      - order
    get:
      consumes:
      - application/json
      description: Get order by id
      parameters:
      - description: Order ID
        in: path
        name: orderId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mongoModels.Order'
      security:
      - BearerAuth: []
      summary: Get order by id
      tags:
      - order
  /all:
    get:
      consumes:
      - application/json
      description: Get all orders
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/mongoModels.Order'
              type: array
            type: array
      security:
      - BearerAuth: []
      summary: Get all orders
      tags:
      - order
  /history/{userId}:
    get:
      consumes:
      - application/json
      description: Get order history by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/mongoModels.Order'
              type: array
            type: array
      security:
      - BearerAuth: []
      summary: Get order history by user ID
      tags:
      - order
  /nextStatus/{orderId}:
    put:
      consumes:
      - application/json
      description: Update an order to the next status
      parameters:
      - description: Order ID
        in: path
        name: orderId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Update an order to the next status
      tags:
      - order
securityDefinitions:
  BearerAuth:
    description: Use /login to get your token and use it here
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
