services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: motdepasse
      MYSQL_DATABASE: easeat 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./creation_script.sql:/docker-entrypoint-initdb.d/creation_script.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - easeat-net

networks:
  easeat-net:
    external: true
