basePath: /restaurant
definitions:
  model.Menuitem:
    properties:
      created_at:
        type: string
      description:
        type: string
      id_menu_item:
        type: integer
      id_restaurant:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  model.Restaurant:
    properties:
      address:
        type: string
      id_restaurant:
        type: integer
      localisation_latitude:
        type: number
      localisation_longitude:
        type: number
      name:
        type: string
      opening_hours:
        type: string
      phone:
        type: string
      picture:
        type: string
    type: object
host: localhost:8052
info:
  contact:
    email: benjamin.guerre@viacesi.fr
    name: Groupe 2 FISA INFO A4 CESI (2025)
    url: https://contact.easeat.fr
  description: This is a microservice for managing restaurants
  title: Swagger Easeat restaurant microservice
  version: "2.0"
paths:
  /restaurant/{restaurantId}:
    get:
      consumes:
      - application/json
      description: Get a restaurant by its id
      parameters:
      - description: Restaurant ID
        in: path
        name: restaurantId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Restaurant'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get a restaurant by its id
      tags:
      - restaurant
  /restaurant/{restaurantId}/menuitems:
    get:
      consumes:
      - application/json
      description: Get menu items by restaurant id
      parameters:
      - description: Restaurant ID
        in: path
        name: restaurantId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Menuitem'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get menu items by restaurant id
      tags:
      - restaurant
  /restaurant/nearby/{latitude}/{longitude}/{kmAround}:
    get:
      consumes:
      - application/json
      description: Get nearby restaurants from the user's location
      parameters:
      - description: Latitude of the user
        in: path
        name: latitude
        required: true
        type: string
      - description: Longitude of the user
        in: path
        name: longitude
        required: true
        type: string
      - description: Distance around the user in km
        in: path
        name: kmAround
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Restaurant'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get nearby restaurants
      tags:
      - restaurant
securityDefinitions:
  BearerAuth:
    description: Use /login to get your token and use it here
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
