basePath: /api
host: localhost:8080
info:
  contact:
    email: benjamin.guerre@viacesi.fr
    name: Groupe 2 FISA INFO A4 CESI (2025)
    url: https://contact.easeat.fr
  description: This is the API for application Easeat. It's for commande food in the
    restaurant.
  title: Swagger Easeat API
  version: "2.0"
paths:
  /test:
    get:
      description: Testing route isn't use
      responses: {}
      summary: Testing route
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
