name: Generate Go Documentation

on:
  push:
    branches:
      - main
jobs:
  generate-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Godocdown
        run: go install github.com/robertkrimen/godocdown/godocdown@latest
      
      - name: Generate Markdown Documentation
        run: |
          mkdir -p docs
          godocdown . > docs/README.md



      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-docs
          path: docs/
