name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run:  |
                cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
                go mod tidy

      - name: Run tests
        run: go test ./... -v
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.1"  # Version stable de Go
  
      - name: Clean Go environment
        run: |
          go clean -modcache
          rm -rf $GOPATH/pkg
  
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.52.2
  
      - name: Install dependencies
        run: |
          cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
          go mod tidy
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g /main.go
          go list -m all | grep swaggo || echo "Swaggo non trouvé"
          go get -u github.com/swaggo/gin-swagger
          go get -u github.com/swaggo/files
          go mod tidy
          go mod vendor
  
      - name: Run lint
        run: |
          cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
          golangci-lint run ./...
