name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run:  |
                cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
                go mod tidy

      - name: Run tests
        run: |
          cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
          go test ./... -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"  # Use stable Go version for compatibility
  
      - name: Clean Go environment
        run: |
          go clean -modcache
          rm -rf $GOPATH/pkg
  
      - name: Install latest golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin latest
  
      - name: Install dependencies
        run: |
          cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
          go mod tidy
          go mod vendor
  
      - name: Run lint in debug mode
        run: |
          cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
          golangci-lint run --verbose --timeout=5m ./...

  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Run k6 local test
          uses: grafana/k6-action@v0.3.1
          with:
            filename: my-load-test.js
            flags: --vus 50 --duration 10s
