name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
  
      - name: Install golangci-lint
        run: |
          wget https://github.com/golangci/golangci-lint/releases/download/v1.55.2/golangci-lint-1.55.2-linux-amd64.tar.gz
          tar -xvzf golangci-lint-1.55.2-linux-amd64.tar.gz
          mv golangci-lint-1.55.2-linux-amd64/golangci-lint /usr/local/bin/

      - name: Install dependencies
        run: |
          cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
          go mod tidy
          go mod vendor
          go build ./...
  
      - name: Generate Swagger Docs
        run: |
          cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init || echo "⚠️  Warning: swag init a échoué, vérifiez main.go"
  
      - name: Run lint
        run: |
          cd /home/runner/work/Web_Avance_CESI/Web_Avance_CESI/backend/apiGateway/
          $(go env GOPATH)/bin/golangci-lint run ./...
